# Generated by Django 3.0.6 on 2020-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='users/%y/%m/%d'),
        ),
    ]
